// src/app/Components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpService } from 'src/app/Services/http.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  token: any;

  constructor(private http: HttpService, private _router: Router) { }

  signin(email: any, password: any) {

    this.http.login({email, password}).subscribe({
      next: (res) => {
        localStorage.setItem('token', JSON.stringify(res))
        this.token = JSON.parse(localStorage.getItem('token') as string).accessToken
        this._router.navigateByUrl('/home')
      },
      error: (err) => {
        console.log(err)
      }
    })
  }

  ngOnInit(): void {
    
  }
}

<div class="login">
    <div class="login-container">

        <form action="post" class="form-group">

            <label for="email">Email</label>
            <input #email type="email" id="email" class="form-control" required>

            <!-- <input type="hidden" name="" [value]="token"> -->
            <label for="password">Password</label>
            <input #password type="password" id="password" class="form-control" required>

            <div class="submitbtn">
                <input (click)="signin(email.value, password.value)" type="submit" value="Login" class="btn btn-primary">
            </div>

            <div class="signupalter">
                <span>don't have account?</span><a routerLink="/signup">signup</a>
            </div>

        </form>

    </div>
</div>

// src/components/Login/Login.jsx
import classes from './Login.module.css'
import Modal from '../Modal/Modal'
import { Form, redirect } from 'react-router-dom'
import axios from 'axios';

function Login() {
    return (
        <Modal>
            <Form method='post' className={classes.form}>
                <p>
                    <label htmlFor="email">email</label>
                    <input type="email" id='email' name='email' required />
                </p>
                <p>
                    <label htmlFor="password">password</label>
                    <input type="password" id='password' name='password' required />
                </p>
                <p className={classes.actions}>
                    <button type='submit'>Submit</button>
                </p>
            </Form>
        </Modal>
    );
}

export default Login;

export async function action({request}) {
    const formData = await request.formData();
    const signupData = Object.fromEntries(formData);
    try {
        const res = await axios.post('http://localhost:3000/users/login', signupData);
        console.log(res);
        localStorage.setItem('token', res.data.accessToken)
    } catch (err) {
        console.log(err)
    }
    return redirect('.');
}
